AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Back-end resources for flappy mo

Parameters:
  CacheName:
    Type: String
    Default: game
  TopicName:
    Type: String
    Default: flappy-mo

Globals:
  Function:
    Runtime: nodejs20.x
    Architectures:
      - arm64
    Tracing: Active
    Timeout: 15
    MemorySize: 1024
    Handler: index.handler
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  StartGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/start-game
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: "{{resolve:ssm:/serverless-toolbox/secrets}}"
      Environment:
        Variables:
          SECRET_ID: "{{resolve:ssm:/serverless-toolbox/secrets}}"
          CACHE_NAME: !Ref CacheName
          TOPIC_NAME: !Ref TopicName
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - index.mjs
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
        External:
          - '@aws-sdk/client-secrets-manager'

  StartGameStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      DefinitionUri: state machines/start-new-game.asl.json
      DefinitionSubstitutions:
        LambdaInvoke: !Sub arn:${AWS::Partition}:states:::lambda:invoke
        StartGameFunction: !GetAtt StartGameFunction.Arn
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: !GetAtt StartGameFunction.Arn

  StartGameScheduleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PublishTopContent
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !GetAtt StartGameStateMachine.Arn

  StartGameSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Trigger the Start Game State Machine every minute
      FlexibleTimeWindow:
        Mode: 'OFF'
      Name: TriggerStartGameStateMachine
      ScheduleExpression: rate(1 minute)
      Target:
        Arn: !GetAtt StartGameStateMachine.Arn
        RoleArn: !GetAtt StartGameScheduleRole.Arn

  EnableDisableGameStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      DefinitionUri: state machines/enable-disable-game.asl.json
      DefinitionSubstitutions:
        GetSchedule: !Sub arn:${AWS::Partition}:states:::aws-sdk:scheduler:getSchedule
        UpdateSchedule: !Sub arn:aws:states:::aws-sdk:scheduler:updateSchedule
        ScheduleName: !Ref StartGameSchedule
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - scheduler:GetSchedule
                - scheduler:UpdateSchedule
              Resource: !GetAtt StartGameSchedule.Arn
            - Effect: Allow
              Action: iam:PassRole
              Resource: !GetAtt StartGameScheduleRole.Arn
      Events:
        Enable:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(0 6 * * ? *)
            ScheduleExpressionTimezone: America/Chicago
            Input: "{\"state\":\"ENABLED\"}"
        Disable:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(0 23 * * ? *)
            ScheduleExpressionTimezone: America/Chicago
            Input: "{\"state\":\"DISABLED\"}"
